spring:
  application:
    name: mymac
  security:
    user:
      name: admin
      password: admin
    basic:
      enabled: true

server:
  port: 8761

eureka:
  instance:
    hostname: mymac.minclouds.cn
    healthCheckUrlPath: /health
    preferIpAddress: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    region: default
    availabilityZones:
      default: chendu
    useDnsForFetchingServiceUrls: true
    serviceUrl:
      defaultZone: http://admin:admin@mymac.minclouds.cn:8761/eureka
    eurekaServerDNSName: eureka.autumn.org.cn
    eurekaServerURLContext: eureka
    eurekaServerPort: 8761
    preferSameZoneEureka: true

    registerWithEureka: true
    fetchRegistry: true
    transport:
      applicationsResolverUseIp: false
